// Generated by https://quicktype.io

export interface OpcionesGenerales {
	ERROR:      boolean;
	ESTADOS:    Categoria[];
	CATEGORIAS: Categoria[];
	USO_CFDI:   Categoria[];
}

export interface Categoria {
	VALUE: string;
	TEXT:  string;
}
